### ISSUE TITLE
How to enable swagger for production?

### ISSUE THREAD

**Issue by urza** [DamianEdwards/MinimalApiPlayground#16]
How to enable swagger for production as well? In EF.Core example, I expected that since swagger isn't inside "is development environment" condition, that it will be enabled also in production, but it is not.

**Comment by urza** [comment]
My mistake, swagger works in production as well, you just have to go to /swagger manually, in my project it was redirecting there in dev environment automatically and I didnt realize this.

**Comment by mohammed-source** [comment]
Khankgrandfull

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
