### ISSUE TITLE
Possible to have a Bind method in the IParameterBinder interface

### ISSUE THREAD

**Issue by jzs11** [DamianEdwards/MinimalApiPlayground#19]
In my scenario, I don't need to use async to fetch the JSON content. thanks.

![image](https://user-images.githubusercontent.com/2770401/162550387-5e35e309-836d-4933-99e8-ffb347fe34e6.png)

**Comment by jzs11** [comment]
I know I can do sth like

return ValueTask.FromResult(option); 

Just feel little bit wired to use BindAsync

**Comment by DamianEdwards** [comment]
Due to the nature of `async` and the issues caused by inducing sync over async calls on the sum of it it's simply better to leave these kinds of extensibility points `async` only. It already returns `ValueTask` so there's effectively no penalty for returning synchronously.

**Comment by jzs11** [comment]
Thanks for your insight on the performance side with ValueTask.
