### ISSUE TITLE
Using MapGet for error handlers doesn't work for unhandled errors thrown in Post endpoints

### ISSUE THREAD

**Issue by phaselden** [DamianEdwards/MinimalApiPlayground#20]
Hi Damian,

Firstly, thanks for this very helpful repository, and everything else you do at Microsoft.

Secondly, in my .NET 6 Web API code I found that using MapGet like this:
    `app.MapGet("/error", (HttpContext context) =>...`
would not capture exceptions thrown in POST requests. Instead, a 405 would always be returned.

Changing it to Map like the following seemed to fix it:
   `app.Map("/error", (HttpContext context) =>...`

To check it was not just my code, I cloned this repository, added the following, and observed the same behavior:
```
app.MapPost("/throw/{statusCode?}", (int? statusCode) =>
    {
        throw statusCode switch
        {
            >= 400 and < 500 => new BadHttpRequestException(
                $"{statusCode} {ReasonPhrases.GetReasonPhrase(statusCode.Value)}",
                statusCode.Value),
            _ => throw new Exception("uh oh")
        };
    })
    .WithTags("Examples");
```
(BTW - did you mean to include the 2nd `throw` in the switch's default?)

Cheers, 
Phil 
(Melbourne)

**Comment by DamianEdwards** [comment]
Thanks Phil. Good pickup on the error endpoint, that should indeed be a `Map` call, and yeah I have an extra `throw` in the throw endpoint too 😄
